#!/bin/sh
set -eu

# create user needed for certain edit actions (only has effect on the first go)
docker-compose run --rm repo \
	php /var/www/html/maintenance/createAndPromote.php --wiki default --bureaucrat --sysop --bot selenium test1234 \
	|| true

docker-compose run --rm seleniumtests \
	node_modules/.bin/wdio tests/selenium/wdio.conf.js --mochaOpts.timeout=60000 --host selenium
