version: '3'

networks:
  default:
    external:
      name: mediawiki

volumes:
  db_data: ~

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: repo

  repo:
    build: ./
    depends_on:
      - mysql
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"

  nodejs:
    build: ./vue-template-service
    volumes:
      - ./vue-template-service:/usr/src/app
    ports:
      - "3000:3000"

  seleniumtests:
    image: "node:6"
    environment:
      - "MW_SERVER=http://repo"
      - "MW_SCRIPT_PATH=/"
      - "MEDIAWIKI_USER=selenium"
      - "MEDIAWIKI_PASSWORD=test1234"
    command: echo 'invoke me through ./browsertest'
    working_dir: /app
    volumes:
      - "./web:/app"
      - "${SELENIUM_LOG_PATH}:/app/log"
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    depends_on:
      - repo
#    ports:
#      - 80
